// Generated by Melange

import * as Melange__Playwright from "./Playwright.js";

function run_tests(helpers) {
  helpers.test("renders calendar board (OCaml)", (function (fixtures) {
          return fixtures.mount(helpers.board).then(function (component) {
                      return Melange__Playwright.to_be_visible(helpers.expect(component));
                    });
        }));
  helpers.test("displays month names (OCaml)", (function (fixtures) {
          return fixtures.mount(helpers.board).then(function (component) {
                      const jan = Melange__Playwright.get_by_text(component, "Jan");
                      return Melange__Playwright.to_be_visible(helpers.expect(jan));
                    });
        }));
}

export {
  run_tests ,
}
/* No side effect */
