// Generated by Melange

import * as Caml_array from "melange.js/caml_array.js";
import * as Melange__Playwright from "./Playwright.js";
import * as Packaday__Board from "packaday/Board.js";
import * as JsxRuntime from "react/jsx-runtime";

const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];

function run_tests(helpers) {
  helpers.describe("Board Component", (function (param) {
          helpers.test("renders board (direct mount)", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount_element(JsxRuntime.jsx(Packaday__Board.make, Packaday__Board.makeProps(undefined, undefined))), (function (component) {
                                return Melange__Playwright.to_be_visible(helpers.expect(component));
                              }));
                }));
          helpers.test("renders board", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount(helpers.board), (function (component) {
                                return Melange__Playwright.to_be_visible(helpers.expect(component));
                              }));
                }));
          helpers.test("month tiles display correctly", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount(helpers.board), (function (component) {
                                const check_month = function (i) {
                                  const month = Caml_array.get(months, i);
                                  const el = Melange__Playwright.get_by_text_opt(component, month, Melange__Playwright.get_by_text_options(true, undefined));
                                  return Melange__Playwright.to_be_visible(helpers.expect(el));
                                };
                                return Melange__Playwright.let$great(check_month(0), (function (param) {
                                              return Melange__Playwright.let$great(check_month(1), (function (param) {
                                                            return Melange__Playwright.let$great(check_month(2), (function (param) {
                                                                          return Melange__Playwright.let$great(check_month(3), (function (param) {
                                                                                        return Melange__Playwright.let$great(check_month(4), (function (param) {
                                                                                                      return Melange__Playwright.let$great(check_month(5), (function (param) {
                                                                                                                    return Melange__Playwright.let$great(check_month(6), (function (param) {
                                                                                                                                  return Melange__Playwright.let$great(check_month(7), (function (param) {
                                                                                                                                                return Melange__Playwright.let$great(check_month(8), (function (param) {
                                                                                                                                                              return Melange__Playwright.let$great(check_month(9), (function (param) {
                                                                                                                                                                            return Melange__Playwright.let$great(check_month(10), (function (param) {
                                                                                                                                                                                          return check_month(11);
                                                                                                                                                                                        }));
                                                                                                                                                                          }));
                                                                                                                                                            }));
                                                                                                                                              }));
                                                                                                                                }));
                                                                                                                  }));
                                                                                                    }));
                                                                                      }));
                                                                        }));
                                                          }));
                                            }));
                              }));
                }));
          helpers.test("day tiles display correctly", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount(helpers.board), (function (component) {
                                const check_days = function (day) {
                                  if (day > 31) {
                                    return Promise.resolve(undefined);
                                  }
                                  const el = Melange__Playwright.get_by_text_opt(component, String(day), Melange__Playwright.get_by_text_options(true, undefined));
                                  return Melange__Playwright.let$great(Melange__Playwright.to_be_visible(helpers.expect(el)), (function (param) {
                                                return check_days(day + 1 | 0);
                                              }));
                                };
                                return check_days(1);
                              }));
                }));
          helpers.test("correct total tile count", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount(helpers.board), (function (component) {
                                const tiles = Melange__Playwright.locator_(component, ".tile");
                                return Melange__Playwright.to_have_count(helpers.expect(tiles), 43);
                              }));
                }));
          helpers.test("visual snapshot", (function (fixtures) {
                  return Melange__Playwright.let$great(fixtures.mount(helpers.board), (function (component) {
                                const jan = Melange__Playwright.get_by_text(component, "Jan");
                                return Melange__Playwright.let$great(Melange__Playwright.to_be_visible(helpers.expect(jan)), (function (param) {
                                              const day31 = Melange__Playwright.get_by_text_opt(component, "31", Melange__Playwright.get_by_text_options(true, undefined));
                                              return Melange__Playwright.let$great(Melange__Playwright.to_be_visible(helpers.expect(day31)), (function (param) {
                                                            return Melange__Playwright.to_have_screenshot(helpers.expect(component), "board.png");
                                                          }));
                                            }));
                              }));
                }));
        }));
}

export {
  run_tests ,
}
/* Packaday__Board Not a pure module */
