// Generated by Melange

import * as Caml_option from "melange.js/caml_option.js";

function get_by_text_options(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.exact = Caml_option.valFromOption(prim0);
  }
  return tmp;
}

function mouse(prim) {
  return prim.mouse;
}

function mouse_move(prim0, prim1, prim2) {
  return prim0.move(prim1, prim2);
}

function click(prim) {
  return prim.click();
}

function hover(prim) {
  return prim.hover();
}

function get_by_text(prim0, prim1) {
  return prim0.getByText(prim1);
}

function get_by_text_opt(prim0, prim1, prim2) {
  return prim0.getByText(prim1, prim2);
}

function locator_(prim0, prim1) {
  return prim0.locator(prim1);
}

function first(prim) {
  return prim.first();
}

function to_be_visible(prim) {
  return prim.toBeVisible();
}

function to_have_count(prim0, prim1) {
  return prim0.toHaveCount(prim1);
}

function to_have_screenshot(prim0, prim1) {
  return prim0.toHaveScreenshot(prim1);
}

function to_have_attribute(prim0, prim1, prim2) {
  return prim0.toHaveAttribute(prim1, prim2);
}

function to_have_class(prim0, prim1) {
  return prim0.toHaveClass(prim1);
}

function to_have_css(prim0, prim1, prim2) {
  return prim0.toHaveCSS(prim1, prim2);
}

export {
  get_by_text_options ,
  mouse ,
  mouse_move ,
  click ,
  hover ,
  get_by_text ,
  get_by_text_opt ,
  locator_ ,
  first ,
  to_be_visible ,
  to_have_count ,
  to_have_screenshot ,
  to_have_attribute ,
  to_have_class ,
  to_have_css ,
}
/* No side effect */
