// Generated by Melange


function click(prim) {
  return prim.click();
}

function hover(prim) {
  return prim.hover();
}

function get_by_text(prim0, prim1) {
  return prim0.getByText(prim1);
}

function locator_(prim0, prim1) {
  return prim0.locator(prim1);
}

function to_be_visible(prim) {
  return prim.toBeVisible();
}

function to_have_count(prim0, prim1) {
  return prim0.toHaveCount(prim1);
}

function to_have_screenshot(prim0, prim1) {
  return prim0.toHaveScreenshot(prim1);
}

export {
  click ,
  hover ,
  get_by_text ,
  locator_ ,
  to_be_visible ,
  to_have_count ,
  to_have_screenshot ,
}
/* No side effect */
